import {
  access,
  copyFile,
  mkdir,
  readdir,
  readFile,
  rm,
  writeFile
} from "node:fs/promises";
import path from "node:path";

import type { DailyKanjiDataset } from "../types.ts";

export const dailyKanjiAudioGeneratedMarker = ".daily-kanji-audio-generated";
const dailyKanjiAudioSafeStemMaxLength = 72;
const dailyKanjiKnownAudioSourceExtensions = new Set([
  ".aac",
  ".m4a",
  ".mp3",
  ".ogg",
  ".wav"
]);
const dailyKanjiIosPlayableAudioExtensions = new Set([
  ".aac",
  ".m4a",
  ".mp3",
  ".wav"
]);

export type DailyKanjiAudioMissingFile = {
  audioSrc: string;
  cardId: string;
  mediaSlug: string;
  sourcePath: string;
};

export type DailyKanjiAudioUnsupportedFile = {
  audioSrc: string;
  cardId: string;
  extension: string;
  mediaSlug: string;
};

export type DailyKanjiAudioCopyResult = {
  copied: number;
  missing: DailyKanjiAudioMissingFile[];
  outputRoot: string;
  unsupported: DailyKanjiAudioUnsupportedFile[];
};

type DailyKanjiAudioAssetPaths = {
  outputPath: string;
  outputRelativePath: string;
  sourcePath: string;
};

type DailyKanjiAudioReference = {
  audioSrc: string;
  cardId: string;
  mediaSlug: string;
};

export async function copyDailyKanjiAudioAssets(input: {
  contentRoot: string;
  dataset: DailyKanjiDataset;
  outputRoot: string;
}): Promise<DailyKanjiAudioCopyResult> {
  const outputRoot = path.resolve(input.outputRoot);
  const { playableReferences, unsupported } =
    collectDailyKanjiAudioReferences(input.dataset);
  const plannedCopies = playableReferences.map((reference) => ({
    ...reference,
    paths: resolveDailyKanjiAudioAssetPaths({
      audioSrc: reference.audioSrc,
      contentRoot: input.contentRoot,
      mediaSlug: reference.mediaSlug,
      outputRoot
    })
  }));
  assertNoDuplicateOutputPaths(plannedCopies);

  const missing = await listMissingAudioFiles(plannedCopies);

  if (missing.length > 0) {
    await removeGeneratedOutputRootIfPresent(outputRoot);

    return {
      copied: 0,
      missing,
      outputRoot,
      unsupported
    };
  }

  await prepareGeneratedOutputRoot(outputRoot);
  await writeFile(
    path.join(outputRoot, dailyKanjiAudioGeneratedMarker),
    "Generated by scripts/export-daily-kanji-ios-audio.ts. Do not edit.\n",
    "utf8"
  );

  for (const copy of plannedCopies) {
    await mkdir(path.dirname(copy.paths.outputPath), { recursive: true });
    await copyFile(copy.paths.sourcePath, copy.paths.outputPath);
  }

  return {
    copied: plannedCopies.length,
    missing: [],
    outputRoot,
    unsupported
  };
}

export function resolveDailyKanjiAudioAssetPaths(input: {
  audioSrc: string;
  contentRoot: string;
  mediaSlug: string;
  outputRoot: string;
}): DailyKanjiAudioAssetPaths {
  assertSafeMediaSlug(input.mediaSlug);
  assertSafeAudioSrc(input.audioSrc);
  assertIosPlayableAudioSrc(input.audioSrc);

  const audioParts = input.audioSrc.split("/");
  const contentMediaRoot = path.resolve(
    input.contentRoot,
    "media",
    input.mediaSlug
  );
  const sourcePath = path.resolve(contentMediaRoot, ...audioParts);
  const outputRoot = path.resolve(input.outputRoot);
  const outputRelativePath = buildDailyKanjiAudioBundleFileName({
    audioSrc: input.audioSrc,
    mediaSlug: input.mediaSlug
  });
  const outputPath = path.resolve(outputRoot, outputRelativePath);

  assertPathInside(sourcePath, contentMediaRoot, "audio source");
  assertPathInside(outputPath, outputRoot, "audio output");

  return {
    outputPath,
    outputRelativePath,
    sourcePath
  };
}

export function buildDailyKanjiAudioBundleFileName(input: {
  audioSrc: string;
  mediaSlug: string;
}) {
  assertSafeMediaSlug(input.mediaSlug);
  assertSafeAudioSrc(input.audioSrc);
  assertIosPlayableAudioSrc(input.audioSrc);

  const extension = path.posix.extname(input.audioSrc);
  const stem = input.audioSrc.slice(
    0,
    input.audioSrc.length - extension.length
  );
  const safeStem =
    sanitizeDailyKanjiAudioFileNameStem(stem)
      .slice(0, dailyKanjiAudioSafeStemMaxLength)
      .replace(/^_+|_+$/gu, "") || "audio";
  const hash = hashDailyKanjiAudioPath(input.audioSrc);

  return `daily-kanji-audio__${input.mediaSlug}__${safeStem}__${hash}${extension}`;
}

function sanitizeDailyKanjiAudioFileNameStem(stem: string) {
  return stem.replace(/[^A-Za-z0-9-]/gu, "_");
}

function hashDailyKanjiAudioPath(audioSrc: string) {
  let hash = 0xcbf29ce484222325n;
  const fnvPrime = 0x100000001b3n;
  const uint64Mask = 0xffffffffffffffffn;

  for (const byte of Buffer.from(audioSrc, "utf8")) {
    hash ^= BigInt(byte);
    hash = (hash * fnvPrime) & uint64Mask;
  }

  return hash.toString(16).padStart(16, "0");
}

async function listMissingAudioFiles(
  plannedCopies: Array<
    DailyKanjiAudioReference & { paths: DailyKanjiAudioAssetPaths }
  >
) {
  const missing: DailyKanjiAudioMissingFile[] = [];

  for (const copy of plannedCopies) {
    try {
      await access(copy.paths.sourcePath);
    } catch {
      missing.push({
        audioSrc: copy.audioSrc,
        cardId: copy.cardId,
        mediaSlug: copy.mediaSlug,
        sourcePath: copy.paths.sourcePath
      });
    }
  }

  return missing;
}

function assertNoDuplicateOutputPaths(
  plannedCopies: Array<
    DailyKanjiAudioReference & { paths: DailyKanjiAudioAssetPaths }
  >
) {
  const byOutputRelativePath = new Map<
    string,
    DailyKanjiAudioReference & { paths: DailyKanjiAudioAssetPaths }
  >();

  for (const copy of plannedCopies) {
    const previous = byOutputRelativePath.get(copy.paths.outputRelativePath);

    if (!previous) {
      byOutputRelativePath.set(copy.paths.outputRelativePath, copy);
      continue;
    }

    if (previous.paths.sourcePath !== copy.paths.sourcePath) {
      throw new Error(
        [
          "Daily Kanji audio output collision:",
          previous.paths.outputRelativePath,
          previous.paths.sourcePath,
          copy.paths.sourcePath
        ].join(" ")
      );
    }
  }
}

function collectDailyKanjiAudioReferences(
  dataset: DailyKanjiDataset
): {
  playableReferences: DailyKanjiAudioReference[];
  unsupported: DailyKanjiAudioUnsupportedFile[];
} {
  const playableByDestination = new Map<string, DailyKanjiAudioReference>();
  const unsupportedByDestination = new Map<
    string,
    DailyKanjiAudioUnsupportedFile
  >();

  for (const card of dataset.cards) {
    const audioSrc = card.entry.audioSrc;

    if (!audioSrc) {
      continue;
    }

    assertSafeMediaSlug(card.media.slug);
    assertSafeAudioSrc(audioSrc);

    const key = `${card.media.slug}/${audioSrc}`;

    if (!isIosPlayableAudioSrc(audioSrc)) {
      if (!unsupportedByDestination.has(key)) {
        unsupportedByDestination.set(key, {
          audioSrc,
          cardId: card.cardId,
          extension: path.posix.extname(audioSrc).toLowerCase(),
          mediaSlug: card.media.slug
        });
      }

      continue;
    }

    if (!playableByDestination.has(key)) {
      playableByDestination.set(key, {
        audioSrc,
        cardId: card.cardId,
        mediaSlug: card.media.slug
      });
    }
  }

  return {
    playableReferences: [...playableByDestination.values()],
    unsupported: [...unsupportedByDestination.values()]
  };
}

async function prepareGeneratedOutputRoot(outputRoot: string) {
  if (await pathExists(outputRoot)) {
    await assertGeneratedOutputRoot(outputRoot);
    await rm(outputRoot, { force: true, recursive: true });
  }

  await mkdir(outputRoot, { recursive: true });
}

async function removeGeneratedOutputRootIfPresent(outputRoot: string) {
  if (!(await pathExists(outputRoot))) {
    return;
  }

  await assertGeneratedOutputRoot(outputRoot);
  await rm(outputRoot, { force: true, recursive: true });
}

async function assertGeneratedOutputRoot(outputRoot: string) {
  const entries = await readdir(outputRoot);

  if (entries.length === 0) {
    return;
  }

  const markerPath = path.join(outputRoot, dailyKanjiAudioGeneratedMarker);

  try {
    const marker = await readFile(markerPath, "utf8");

    if (
      marker.startsWith("Generated by scripts/export-daily-kanji-ios-audio.ts.")
    ) {
      return;
    }
  } catch {
    // Fall through to the refusal below.
  }

  throw new Error(
    `Refusing to overwrite non-generated Daily Kanji audio directory: ${outputRoot}`
  );
}

async function pathExists(filePath: string) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function assertSafeMediaSlug(mediaSlug: string) {
  if (!/^[a-z0-9][a-z0-9-]*$/u.test(mediaSlug)) {
    throw new Error(`Unsafe Daily Kanji media slug: ${mediaSlug}`);
  }
}

function assertSafeAudioSrc(audioSrc: string) {
  const normalized = path.posix.normalize(audioSrc);
  const extension = path.posix.extname(audioSrc).toLowerCase();

  if (
    audioSrc.length === 0 ||
    audioSrc.includes("\\") ||
    audioSrc.startsWith("/") ||
    !audioSrc.startsWith("assets/audio/") ||
    !dailyKanjiKnownAudioSourceExtensions.has(extension) ||
    normalized !== audioSrc ||
    audioSrc.split("/").some((part) => part === ".." || part.length === 0)
  ) {
    throw new Error(`Unsafe Daily Kanji audio_src: ${audioSrc}`);
  }
}

function isIosPlayableAudioSrc(audioSrc: string) {
  return dailyKanjiIosPlayableAudioExtensions.has(
    path.posix.extname(audioSrc).toLowerCase()
  );
}

function assertIosPlayableAudioSrc(audioSrc: string) {
  if (!isIosPlayableAudioSrc(audioSrc)) {
    throw new Error(`Unsupported Daily Kanji iOS audio_src: ${audioSrc}`);
  }
}

function assertPathInside(filePath: string, rootPath: string, label: string) {
  const relative = path.relative(rootPath, filePath);

  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`Resolved Daily Kanji ${label} path escapes its root.`);
  }
}
