import { mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

import {
  buildAgentOrientationDocument,
  discoverRepoScopedSkills,
  taskClassifiers
} from "../scripts/generate-agent-orientation";

describe("agent orientation generator", () => {
  it("discovers repo-scoped skills from SKILL.md frontmatter", async () => {
    const tempRoot = path.join(
      tmpdir(),
      `jcs-agent-orientation-${process.pid}-${Date.now()}`
    );

    try {
      await mkdir(path.join(tempRoot, ".agents", "skills", "sample-skill"), {
        recursive: true
      });
      await mkdir(path.join(tempRoot, ".agents", "skills", "missing-doc"), {
        recursive: true
      });
      await writeFile(
        path.join(tempRoot, ".agents", "skills", "sample-skill", "SKILL.md"),
        `---
name: sample-skill
description: Handles a sample repo workflow.
---

# Sample Skill
`
      );

      const skills = await discoverRepoScopedSkills(tempRoot);

      expect(skills).toEqual([
        {
          name: "sample-skill",
          description: "Handles a sample repo workflow.",
          path: ".agents/skills/sample-skill/SKILL.md"
        }
      ]);
    } finally {
      await rm(tempRoot, { recursive: true, force: true });
    }
  });

  it("generates the task-oriented sections agents need before editing", () => {
    const markdown = buildAgentOrientationDocument({
      skills: [
        {
          name: "forvo-pronunciations",
          description: "Resolve pronunciation audio.",
          path: ".agents/skills/forvo-pronunciations/SKILL.md"
        }
      ]
    });

    expect(markdown).toContain(
      "Generated by `./scripts/with-node.sh pnpm docs:agent-orientation`"
    );
    expect(markdown).toContain("## Task Classifier");
    expect(markdown).toContain("## Protected Areas");
    expect(markdown).toContain("## Canonical Wrapper");
    expect(markdown).toContain("## Verification Chooser");
    expect(markdown).toContain("## Repo-Scoped Skills");
    expect(markdown).toContain("## Key Source Docs");
    expect(markdown).toContain("`./scripts/with-node.sh pnpm check`");
    expect(markdown).toContain("`./scripts/with-node.sh pnpm agent:check`");
    expect(markdown).toContain("`./scripts/with-node.sh pnpm test:ios-ops`");
    expect(markdown).toContain(
      "`./scripts/with-node.sh pnpm daily-kanji:test`"
    );
    expect(markdown).toContain("`content/`");
    expect(markdown).toContain("docs/review-domain-boundary.md");
    expect(markdown).toContain("docs/textbook-pronunciation-boundary.md");
    expect(markdown).toContain(".agents/skills/forvo-pronunciations/SKILL.md");
    expect(markdown).toContain(
      "Documentation-only changes: no application gate is mandatory"
    );
    expect(markdown).not.toContain(
      "Documentation-only changes: run `./scripts/with-node.sh pnpm format:check`"
    );
  });

  it("keeps every task classifier tied to source docs and verification", () => {
    expect(taskClassifiers.length).toBeGreaterThanOrEqual(5);

    for (const classifier of taskClassifiers) {
      expect(classifier.task).toBeTruthy();
      expect(classifier.orientation).toBeTruthy();
      expect(classifier.verify).toBeTruthy();
      expect(classifier.sourceDocs.length).toBeGreaterThan(0);
    }
  });
});
