import { execFile } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { verifyDailyKanjiIosResources } from "../scripts/verify-daily-kanji-ios-resources";

const execFileAsync = promisify(execFile);
const verifierScriptPath = path.join(
  process.cwd(),
  "scripts",
  "verify-daily-kanji-ios-resources.ts"
);

describe("daily kanji iOS resource verifier", () => {
  let tempRoot: string;

  beforeEach(async () => {
    tempRoot = await mkdtemp(path.join(tmpdir(), "jcs-daily-kanji-ios-"));
  });

  afterEach(async () => {
    await rm(tempRoot, { force: true, recursive: true });
  });

  it("accepts a fresh packaged personal dataset", async () => {
    await writeDataset(buildDataset({ generatedAt: "2026-06-10T12:00:00.000Z" }));

    await expect(
      verifyDailyKanjiIosResources({
        iosRoot: tempRoot,
        minCards: 1,
        now: new Date("2026-06-11T12:00:00.000Z")
      })
    ).resolves.toMatchObject({
      audioReferences: 0,
      cards: 1,
      generatedAt: "2026-06-10T12:00:00.000Z"
    });
  });

  it("rejects the sample dataset before build or install", async () => {
    await writeDataset(
      buildDataset({
        cardId: "sample-kanji",
        generatedAt: "2026-06-10T12:00:00.000Z",
        notes: "Sample card shown until the personal dataset is exported."
      })
    );

    await expect(
      verifyDailyKanjiIosResources({
        iosRoot: tempRoot,
        minCards: 1,
        now: new Date("2026-06-11T12:00:00.000Z")
      })
    ).rejects.toThrow(/sample card/);
  });

  it("rejects stale resources unless explicitly allowed", async () => {
    await writeDataset(buildDataset({ generatedAt: "2026-06-01T12:00:00.000Z" }));

    await expect(
      verifyDailyKanjiIosResources({
        iosRoot: tempRoot,
        minCards: 1,
        now: new Date("2026-06-11T12:00:00.000Z")
      })
    ).rejects.toThrow(/dataset is stale/);

    await expect(
      verifyDailyKanjiIosResources({
        allowStale: true,
        iosRoot: tempRoot,
        minCards: 1,
        now: new Date("2026-06-11T12:00:00.000Z")
      })
    ).resolves.toMatchObject({ cards: 1 });
  });

  it("rejects missing packaged audio referenced by the dataset", async () => {
    await writeDataset(
      buildDataset({
        audioSrc: "assets/audio/term/personal.mp3",
        generatedAt: "2026-06-10T12:00:00.000Z"
      })
    );
    await mkdir(path.join(tempRoot, "App", "Resources", "Audio"), {
      recursive: true
    });
    await writeFile(
      path.join(
        tempRoot,
        "App",
        "Resources",
        "Audio",
        ".daily-kanji-audio-generated"
      ),
      "Generated by scripts/export-daily-kanji-ios-audio.ts. Do not edit.\n"
    );

    await expect(
      verifyDailyKanjiIosResources({
        iosRoot: tempRoot,
        minCards: 1,
        now: new Date("2026-06-11T12:00:00.000Z")
      })
    ).rejects.toThrow(/Missing packaged Daily Kanji audio/);
  });

  it("runs as a CLI from repository paths that contain spaces", async () => {
    await writeDataset(buildDataset({ generatedAt: "2026-06-10T12:00:00.000Z" }));

    const result = await execFileAsync(process.execPath, [
      "--disable-warning=MODULE_TYPELESS_PACKAGE_JSON",
      "--experimental-strip-types",
      verifierScriptPath,
      "--ios-root",
      tempRoot,
      "--min-cards",
      "1",
      "--now-iso",
      "2026-06-11T12:00:00.000Z"
    ]);

    expect(result.stdout).toContain("Daily Kanji iOS resources verified: 1 card(s)");
  });

  async function writeDataset(dataset: unknown) {
    const resourcesRoot = path.join(tempRoot, "App", "Resources");
    await mkdir(resourcesRoot, { recursive: true });
    await writeFile(
      path.join(resourcesRoot, "daily-kanji-cards.json"),
      JSON.stringify(dataset)
    );
  }
});

function buildDataset(input: {
  audioSrc?: string;
  cardId?: string;
  generatedAt: string;
  notes?: string;
}) {
  return {
    cards: [
      {
        back: "study",
        cardId: input.cardId ?? "card-personal",
        entry: {
          audioSrc: input.audioSrc ?? null,
          id: "term-personal",
          kind: "term",
          label: "学",
          meaning: "study",
          pitchAccent: 0,
          pitchAccentSource: "fixture",
          reading: "がく"
        },
        exampleIt: null,
        exampleJp: null,
        front: "学",
        kanji: ["学"],
        lesson: {
          slug: "lesson",
          title: "Lesson"
        },
        media: {
          slug: "media-one",
          title: "Media One"
        },
        notes: input.notes ?? "Personal exported card.",
        segment: null,
        srs: {
          difficulty: 8,
          dueAt: null,
          lapses: 0,
          lastHardAgainAt: null,
          lastInteractionAt: input.generatedAt,
          lastReviewedAt: null,
          learningSteps: 0,
          priorityReasons: ["high-difficulty"],
          priorityScore: 8,
          recentHardAgainCount: 0,
          reps: 1,
          scheduledDays: 0,
          stability: 1.2,
          state: "review"
        },
        subjectKey: "term:personal"
      }
    ],
    generatedAt: input.generatedAt,
    recentMistakeLookbackDays: 3,
    version: 1
  };
}
