import {
  access,
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  buildDailyKanjiAudioBundleFileName,
  copyDailyKanjiAudioAssets,
  dailyKanjiAudioGeneratedMarker,
  resolveDailyKanjiAudioAssetPaths
} from "@/features/daily-kanji/server/audio-packager";
import type { DailyKanjiDataset } from "@/features/daily-kanji/types";

describe("daily kanji iOS audio packager", () => {
  let tempRoot: string;

  beforeEach(async () => {
    tempRoot = await mkdtemp(path.join(tmpdir(), "jcs-daily-kanji-audio-"));
  });

  afterEach(async () => {
    await rm(tempRoot, { force: true, recursive: true });
  });

  it("copies dataset audio files into a generated iOS resources tree without filename collisions", async () => {
    await writeContentAudio(
      "media-one/assets/audio/term/shared/pronunciation.mp3",
      "one"
    );
    await writeContentAudio(
      "media-two/assets/audio/term/shared/pronunciation.mp3",
      "two"
    );
    await writeContentAudio(
      "media-one/assets/audio/term/shared_pronunciation.mp3",
      "one-underscore"
    );

    const result = await copyDailyKanjiAudioAssets({
      contentRoot: contentRoot(),
      dataset: buildDataset([
        {
          audioSrc: "assets/audio/term/shared/pronunciation.mp3",
          cardId: "card-one",
          mediaSlug: "media-one"
        },
        {
          audioSrc: "assets/audio/term/shared/pronunciation.mp3",
          cardId: "card-two",
          mediaSlug: "media-two"
        },
        {
          audioSrc: "assets/audio/term/shared_pronunciation.mp3",
          cardId: "card-three",
          mediaSlug: "media-one"
        },
        {
          cardId: "card-without-audio",
          mediaSlug: "media-one"
        }
      ]),
      outputRoot: outputRoot()
    });

    expect(result).toEqual({
      copied: 3,
      missing: [],
      outputRoot: outputRoot(),
      unsupported: []
    });
    await expectOutputFile(
      "daily-kanji-audio__media-one__assets_audio_term_shared_pronunciation__ef0721d341f77686.mp3",
      "one"
    );
    await expectOutputFile(
      "daily-kanji-audio__media-two__assets_audio_term_shared_pronunciation__ef0721d341f77686.mp3",
      "two"
    );
    await expectOutputFile(
      "daily-kanji-audio__media-one__assets_audio_term_shared_pronunciation__8341cef0d7d74236.mp3",
      "one-underscore"
    );
    await expectOutputFile(
      dailyKanjiAudioGeneratedMarker,
      "Generated by scripts/export-daily-kanji-ios-audio.ts. Do not edit.\n"
    );
  });

  it("copies glossary media audio files into the generated iOS resources tree", async () => {
    await writeContentAudio(
      "media-one/assets/audio/term/card/pronunciation.mp3",
      "card"
    );
    await writeContentAudio(
      "media-one/assets/audio/term/glossary/pronunciation.mp3",
      "glossary"
    );

    const result = await copyDailyKanjiAudioAssets({
      contentRoot: contentRoot(),
      dataset: buildDataset(
        [
          {
            audioSrc: "assets/audio/term/card/pronunciation.mp3",
            cardId: "card-one",
            mediaSlug: "media-one"
          }
        ],
        {
          entries: [
            {
              id: "term:glossary-one",
              media: [
                {
                  audioSrc: "assets/audio/term/glossary/pronunciation.mp3",
                  entryId: "term-glossary-one",
                  mediaSlug: "media-one",
                  mediaTitle: "Media One",
                  sourceId: "term-glossary-one"
                }
              ]
            }
          ]
        }
      ),
      outputRoot: outputRoot()
    });

    expect(result).toEqual({
      copied: 2,
      missing: [],
      outputRoot: outputRoot(),
      unsupported: []
    });
    await expectOutputFile(
      buildDailyKanjiAudioBundleFileName({
        audioSrc: "assets/audio/term/card/pronunciation.mp3",
        mediaSlug: "media-one"
      }),
      "card"
    );
    await expectOutputFile(
      buildDailyKanjiAudioBundleFileName({
        audioSrc: "assets/audio/term/glossary/pronunciation.mp3",
        mediaSlug: "media-one"
      }),
      "glossary"
    );
  });

  it("reports missing referenced audio files without writing a partial stale tree", async () => {
    await mkdir(outputRoot(), { recursive: true });
    await writeFile(
      path.join(outputRoot(), dailyKanjiAudioGeneratedMarker),
      "Generated by scripts/export-daily-kanji-ios-audio.ts. Do not edit.\n"
    );
    await writeFile(path.join(outputRoot(), "stale.mp3"), "stale");

    const result = await copyDailyKanjiAudioAssets({
      contentRoot: contentRoot(),
      dataset: buildDataset([
        {
          audioSrc: "assets/audio/term/missing.mp3",
          cardId: "missing-card",
          mediaSlug: "media-one"
        }
      ]),
      outputRoot: outputRoot()
    });

    expect(result.copied).toBe(0);
    expect(result.unsupported).toEqual([]);
    expect(result.missing).toEqual([
      {
        audioSrc: "assets/audio/term/missing.mp3",
        mediaSlug: "media-one",
        referenceId: "card:missing-card",
        sourcePath: path.join(
          contentRoot(),
          "media",
          "media-one",
          "assets",
          "audio",
          "term",
          "missing.mp3"
        )
      }
    ]);
    await expectMissingOutput(dailyKanjiAudioGeneratedMarker);
    await expectMissingOutput("stale.mp3");
  });

  it("skips known audio formats that are not playable in the iOS app", async () => {
    await writeContentAudio("media-one/assets/audio/term/settings.ogg", "ogg");
    await writeContentAudio("media-one/assets/audio/term/settings.oga", "oga");

    const result = await copyDailyKanjiAudioAssets({
      contentRoot: contentRoot(),
      dataset: buildDataset([
        {
          audioSrc: "assets/audio/term/settings.ogg",
          cardId: "ogg-card",
          mediaSlug: "media-one"
        },
        {
          audioSrc: "assets/audio/term/settings.oga",
          cardId: "oga-card",
          mediaSlug: "media-one"
        }
      ]),
      outputRoot: outputRoot()
    });

    expect(result).toEqual({
      copied: 0,
      missing: [],
      outputRoot: outputRoot(),
      unsupported: [
        {
          audioSrc: "assets/audio/term/settings.ogg",
          extension: ".ogg",
          mediaSlug: "media-one",
          referenceId: "card:ogg-card"
        },
        {
          audioSrc: "assets/audio/term/settings.oga",
          extension: ".oga",
          mediaSlug: "media-one",
          referenceId: "card:oga-card"
        }
      ]
    });
    await expectOutputFile(
      dailyKanjiAudioGeneratedMarker,
      "Generated by scripts/export-daily-kanji-ios-audio.ts. Do not edit.\n"
    );
    await expectMissingOutput(
      "daily-kanji-audio__media-one__assets_audio_term_settings__728ccf0952652035.ogg"
    );
  });

  it("rejects unsafe and non-audio paths before resolving source or output locations", () => {
    expect(() =>
      resolveDailyKanjiAudioAssetPaths({
        audioSrc: "../escape.mp3",
        contentRoot: contentRoot(),
        mediaSlug: "media-one",
        outputRoot: outputRoot()
      })
    ).toThrow(/Unsafe Daily Kanji audio_src/);

    expect(() =>
      resolveDailyKanjiAudioAssetPaths({
        audioSrc: "/absolute.mp3",
        contentRoot: contentRoot(),
        mediaSlug: "media-one",
        outputRoot: outputRoot()
      })
    ).toThrow(/Unsafe Daily Kanji audio_src/);

    expect(() =>
      resolveDailyKanjiAudioAssetPaths({
        audioSrc: "workflow/notes.mp3",
        contentRoot: contentRoot(),
        mediaSlug: "media-one",
        outputRoot: outputRoot()
      })
    ).toThrow(/Unsafe Daily Kanji audio_src/);

    expect(() =>
      resolveDailyKanjiAudioAssetPaths({
        audioSrc: "assets/audio/term/not-audio.txt",
        contentRoot: contentRoot(),
        mediaSlug: "media-one",
        outputRoot: outputRoot()
      })
    ).toThrow(/Unsafe Daily Kanji audio_src/);

    expect(() =>
      resolveDailyKanjiAudioAssetPaths({
        audioSrc: "assets/audio/term/settings.ogg",
        contentRoot: contentRoot(),
        mediaSlug: "media-one",
        outputRoot: outputRoot()
      })
    ).toThrow(/Unsupported Daily Kanji iOS audio_src/);
  });

  function contentRoot() {
    return path.join(tempRoot, "content");
  }

  function outputRoot() {
    return path.join(tempRoot, "App", "Resources", "Audio");
  }

  async function writeContentAudio(relativePath: string, contents: string) {
    const filePath = path.join(contentRoot(), "media", relativePath);

    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, contents);
  }

  async function expectOutputFile(
    relativePath: string,
    expectedContents: string
  ) {
    const contents = await readFile(
      path.join(outputRoot(), relativePath),
      "utf8"
    );

    expect(contents).toBe(expectedContents);
  }

  async function expectMissingOutput(relativePath: string) {
    await expect(
      access(path.join(outputRoot(), relativePath))
    ).rejects.toThrow();
  }
});

function buildDataset(
  cards: Array<{
    audioSrc?: string;
    cardId: string;
    mediaSlug: string;
  }>,
  glossary?: {
    entries: Array<{
      id: string;
      media: Array<{
        audioSrc?: string;
        entryId: string;
        mediaSlug: string;
        mediaTitle: string;
        sourceId: string;
      }>;
    }>;
  }
): DailyKanjiDataset {
  return {
    cards: cards.map((card) => ({
      back: "back",
      cardId: card.cardId,
      entry: {
        ...(card.audioSrc ? { audioSrc: card.audioSrc } : {}),
        id: `entry-${card.cardId}`,
        kind: "term",
        label: "観点",
        meaning: "meaning"
      },
      front: "観点",
      kanji: ["観", "点"],
      lesson: {
        slug: "lesson-one",
        title: "Lesson One"
      },
      media: {
        slug: card.mediaSlug,
        title: card.mediaSlug
      },
      srs: {
        difficulty: null,
        dueAt: null,
        lapses: 0,
        lastHardAgainAt: null,
        lastInteractionAt: "2026-06-10T12:00:00.000Z",
        lastReviewedAt: null,
        learningSteps: 0,
        priorityReasons: [],
        priorityScore: 0,
        recentHardAgainCount: 0,
        reps: 1,
        scheduledDays: 0,
        stability: null,
        state: "review"
      },
      subjectKey: `term:${card.cardId}`
      })),
    ...(glossary
      ? {
          glossary: {
            entries: glossary.entries.map((entry) => ({
              aliases: [],
              id: entry.id,
              kind: "term",
              label: "観点",
              meaning: "meaning",
              media: entry.media,
              pitchAccent: null,
              pitchAccentSource: null,
              reading: "かんてん",
              romaji: "kanten",
              searchText: "観点 かんてん kanten meaning Media One"
            })),
            entryCount: glossary.entries.length,
            generatedAt: "2026-06-10T12:00:00.000Z",
            version: 1
          }
        }
      : {}),
    generatedAt: "2026-06-10T12:00:00.000Z",
    recentMistakeLookbackDays: 3,
    version: 1
  };
}
