import {
  access,
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  checkMediaAudioAssets,
  mediaAudioGeneratedMarker,
  syncMediaAudioAssets
} from "../scripts/sync-media-audio-assets.ts";

describe("static media audio sync", () => {
  let tempRoot: string;

  beforeEach(async () => {
    tempRoot = await mkdtemp(path.join(tmpdir(), "jcs-media-audio-"));
  });

  afterEach(async () => {
    await rm(tempRoot, { force: true, recursive: true });
  });

  it("copies supported audio files into the generated public tree", async () => {
    await writeSourceFile(
      "sample-media/assets/audio/term/yomu.mp3",
      "mp3 data"
    );
    await writeSourceFile(
      "sample-media/assets/audio/term/yomu.ogg",
      "ogg data"
    );
    await writeSourceFile(
      "sample-media/assets/audio/term/cover.txt",
      "not audio"
    );
    await writeSourceFile(
      "sample-media/assets/images/cover.png",
      "not in audio root"
    );

    const result = await syncMediaAudioAssets(testOptions());

    expect(result.files).toBe(2);
    await expectPublicFile("sample-media/audio/term/yomu.mp3", "mp3 data");
    await expectPublicFile("sample-media/audio/term/yomu.ogg", "ogg data");
    await expectMissingPublicFile("sample-media/audio/term/cover.txt");
    await expectMissingPublicFile("sample-media/images/cover.png");
    await expectPublicFile(
      mediaAudioGeneratedMarker,
      "Generated by scripts/sync-media-audio-assets.ts. Do not edit.\n"
    );
  });

  it("reports missing, stale, and extra files in check mode without mutating", async () => {
    await writeSourceFile(
      "sample-media/assets/audio/term/current.mp3",
      "fresh"
    );
    await writeSourceFile("sample-media/assets/audio/term/stale.mp3", "fresh");
    await syncMediaAudioAssets(testOptions());

    await writePublicFile("sample-media/audio/term/stale.mp3", "old");
    await writePublicFile("sample-media/audio/term/extra.mp3", "extra");
    await rm(publicFile("sample-media/audio/term/current.mp3"));

    const result = await checkMediaAudioAssets(testOptions());

    expect(result.issues).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          path: "sample-media/audio/term/current.mp3",
          type: "missing"
        }),
        expect.objectContaining({
          path: "sample-media/audio/term/stale.mp3",
          type: "stale"
        }),
        expect.objectContaining({
          path: "sample-media/audio/term/extra.mp3",
          type: "extra"
        })
      ])
    );
    await expectPublicFile("sample-media/audio/term/stale.mp3", "old");
  });

  it("refuses to overwrite a non-generated output directory", async () => {
    await writeSourceFile(
      "sample-media/assets/audio/term/yomu.mp3",
      "mp3 data"
    );
    await writePublicFile("manual-file.txt", "keep");

    await expect(syncMediaAudioAssets(testOptions())).rejects.toThrow(
      /not empty and does not contain/
    );
    await expectPublicFile("manual-file.txt", "keep");
  });

  function testOptions() {
    return {
      contentRoot: path.join(tempRoot, "content"),
      publicRoot: path.join(tempRoot, "public")
    };
  }

  async function writeSourceFile(relativePath: string, contents: string) {
    const filePath = path.join(tempRoot, "content", "media", relativePath);

    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, contents);
  }

  async function writePublicFile(relativePath: string, contents: string) {
    const filePath = publicFile(relativePath);

    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, contents);
  }

  async function expectPublicFile(
    relativePath: string,
    expectedContents: string
  ) {
    const contents = await readFile(publicFile(relativePath), "utf8");

    expect(contents).toEqual(expectedContents);
  }

  async function expectMissingPublicFile(relativePath: string) {
    await expect(access(publicFile(relativePath))).rejects.toThrow();
  }

  function publicFile(relativePath: string) {
    return path.join(tempRoot, "public", "media-audio", relativePath);
  }
});
