import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
  unlink,
  writeFile
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";

import {
  importMinimalPairsCorpus,
  validateGeneratedMinimalPairsCorpus
} from "@/features/pitch-accent/tooling";

describe("pitch accent minimal pairs importer", () => {
  it("normalizes upstream base64 audio into AAC files and a lightweight manifest", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "jcs-minimal-pairs-"));
    const sourceDir = path.join(tempDir, "source");
    const outDir = path.join(tempDir, "out");
    const audioBytes = buildAacFixtureBytes();

    try {
      await createFixtureSource(sourceDir, audioBytes);

      const result = await importMinimalPairsCorpus({
        allowNonVendorOutDir: true,
        importedAt: "2026-05-25T00:00:00.000Z",
        outDir,
        repositoryUrl: "https://github.com/Kuuuube/minimal-pairs",
        revision: "fixture",
        sourceDir
      });
      const manifest = JSON.parse(
        await readFile(path.join(outDir, "manifest.json"), "utf8")
      );

      expect(result).toMatchObject({
        audioFileCount: 2,
        pairCount: 1,
        variantCount: 2
      });
      expect(manifest.pairs[0].options[0]).toMatchObject({
        audioMime: "audio/aac",
        audioSrc: "/vendor/minimal-pairs/audio/0/0.aac",
        byteLength: audioBytes.length
      });
      await expect(
        readFile(path.join(outDir, ".minimal-pairs-vendor-generated"), "utf8")
      ).resolves.toContain("Generated by");
      expect(await validateGeneratedMinimalPairsCorpus({ outDir })).toEqual({
        errors: [],
        ok: true
      });

      await unlink(path.join(outDir, "audio", "0", "0.aac"));
      expect(
        (await validateGeneratedMinimalPairsCorpus({ outDir })).errors
      ).toContain("Missing audio file for 0:0.");
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });

  it("refuses to replace non-standard output directories without an explicit allow flag", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "jcs-minimal-pairs-"));
    const sourceDir = path.join(tempDir, "source");
    const outDir = path.join(tempDir, "out");

    try {
      await createFixtureSource(sourceDir, buildAacFixtureBytes());

      await expect(
        importMinimalPairsCorpus({
          importedAt: "2026-05-25T00:00:00.000Z",
          outDir,
          repositoryUrl: "https://github.com/Kuuuube/minimal-pairs",
          revision: "fixture",
          sourceDir
        })
      ).rejects.toThrow("Refusing to replace non-standard");
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });

  it("refuses to replace non-empty custom output directories even with the allow flag", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "jcs-minimal-pairs-"));
    const sourceDir = path.join(tempDir, "source");
    const outDir = path.join(tempDir, "out");

    try {
      await createFixtureSource(sourceDir, buildAacFixtureBytes());
      await mkdir(outDir, { recursive: true });
      await writeFile(path.join(outDir, "keep.txt"), "do not delete\n");

      await expect(
        importMinimalPairsCorpus({
          allowNonVendorOutDir: true,
          importedAt: "2026-05-25T00:00:00.000Z",
          outDir,
          repositoryUrl: "https://github.com/Kuuuube/minimal-pairs",
          revision: "fixture",
          sourceDir
        })
      ).rejects.toThrow("Refusing to replace non-empty custom");
      await expect(
        readFile(path.join(outDir, "keep.txt"), "utf8")
      ).resolves.toBe("do not delete\n");
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });

  it("rejects manifest audio paths that escape the expected pair directory", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "jcs-minimal-pairs-"));
    const outDir = path.join(tempDir, "out");
    const audioBytes = buildAacFixtureBytes();

    try {
      await mkdir(outDir, { recursive: true });
      await writeFile(
        path.join(outDir, "LICENSE-GPL-3.0.txt"),
        "GNU GENERAL PUBLIC LICENSE\nVersion 3\n"
      );
      await writeFile(path.join(outDir, "NOTICE.md"), "Fixture notice.\n");
      await writeFile(
        path.join(outDir, "manifest.json"),
        `${JSON.stringify(buildEscapingManifest(audioBytes), null, 2)}\n`
      );

      const result = await validateGeneratedMinimalPairsCorpus({ outDir });

      expect(result.ok).toBe(false);
      expect(result.errors).toContain(
        "0:0 audio path escapes its pair directory."
      );
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });

  it("rejects unsafe pair ids before resolving manifest audio paths", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "jcs-minimal-pairs-"));
    const outDir = path.join(tempDir, "out");

    try {
      await mkdir(outDir, { recursive: true });
      await writeFile(
        path.join(outDir, "LICENSE-GPL-3.0.txt"),
        "GNU GENERAL PUBLIC LICENSE\nVersion 3\n"
      );
      await writeFile(path.join(outDir, "NOTICE.md"), "Fixture notice.\n");
      await writeFile(
        path.join(outDir, "manifest.json"),
        `${JSON.stringify(buildUnsafePairManifest(), null, 2)}\n`
      );

      const result = await validateGeneratedMinimalPairsCorpus({ outDir });

      expect(result.ok).toBe(false);
      expect(result.errors).toContain("../escape has an unsafe pair id.");
      expect(result.errors).toContain("0:0 audio path has an unsafe pair id.");
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });
});

function buildAacFixtureBytes() {
  return Buffer.from([0xff, 0xf1, 0x50, 0x80, 0x00, 0x1f, 0xfc, 0x00]);
}

async function createFixtureSource(sourceDir: string, audioBytes: Buffer) {
  await mkdir(path.join(sourceDir, "data"), { recursive: true });
  await writeFile(
    path.join(sourceDir, "LICENSE"),
    "GNU GENERAL PUBLIC LICENSE\nVersion 3\n"
  );
  await writeFile(
    path.join(sourceDir, "data", "0"),
    JSON.stringify({
      kana: "とっか",
      pairs: [
        {
          accentedMora: 1,
          moraCount: 3,
          pitchAccent: 1,
          rawPronunciation: "トッカ",
          silencedMoras: [],
          soundData: audioBytes.toString("base64")
        },
        {
          accentedMora: 0,
          moraCount: 3,
          pitchAccent: 0,
          rawPronunciation: "トッカ",
          silencedMoras: [],
          soundData: audioBytes.toString("base64")
        }
      ]
    })
  );
}

function buildEscapingManifest(audioBytes: Buffer) {
  return {
    pairs: [
      {
        hasDevoiced: false,
        id: "0",
        kana: "とっか",
        optionCount: 2,
        options: [
          {
            accentedMora: 1,
            audioMime: "audio/aac",
            audioSha256:
              "a13df0e900a18e28f7260f65f6524f7f1e1fc9c703eac143f3be33e945967e9d",
            audioSrc: "/vendor/minimal-pairs/audio/0/../escape.aac",
            byteLength: audioBytes.length,
            id: "0:0",
            moraCount: 3,
            pitchAccent: 1,
            rawPronunciation: "トッカ",
            silencedMoras: []
          },
          {
            accentedMora: 0,
            audioMime: "audio/aac",
            audioSrc: "/vendor/minimal-pairs/audio/0/1.aac",
            id: "0:1",
            moraCount: 3,
            pitchAccent: 0,
            rawPronunciation: "トッカ",
            silencedMoras: []
          }
        ],
        patternKeys: ["pitch0", "pitch1"]
      }
    ],
    source: {
      importedAt: "2026-05-25T00:00:00.000Z",
      license: "GPL-3.0-only",
      repository: "https://github.com/Kuuuube/minimal-pairs",
      revision: "fixture"
    },
    version: 1
  };
}

function buildUnsafePairManifest() {
  const manifest = buildEscapingManifest(buildAacFixtureBytes());
  manifest.pairs[0]!.id = "../escape";
  manifest.pairs[0]!.options[0]!.audioSrc =
    "/vendor/minimal-pairs/audio/../escape/0.aac";
  manifest.pairs[0]!.options[1]!.audioSrc =
    "/vendor/minimal-pairs/audio/../escape/1.aac";

  return manifest;
}
