import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  getPitchAccentPatternKey,
  validatePitchAccentMinimalPairsCorpus,
  type PitchAccentMinimalPair,
  type PitchAccentMinimalPairsCorpus,
  type PitchAccentPairOption
} from "../model/index.ts";

const GENERATED_MARKER_FILE = ".minimal-pairs-vendor-generated";

export type ImportMinimalPairsCorpusResult = {
  readonly audioFileCount: number;
  readonly pairCount: number;
  readonly variantCount: number;
};

export async function importMinimalPairsCorpus(input: {
  readonly allowNonVendorOutDir?: boolean;
  readonly dryRun?: boolean;
  readonly importedAt?: string;
  readonly outDir: string;
  readonly repositoryUrl: string;
  readonly revision: string;
  readonly sourceDir: string;
}): Promise<ImportMinimalPairsCorpusResult> {
  const importedAt = input.importedAt ?? new Date().toISOString();
  const sourceDataDir = path.join(input.sourceDir, "data");
  const dataFiles = (await readdir(sourceDataDir))
    .filter((fileName) => /^[0-9A-Za-z]+$/u.test(fileName))
    .sort((left, right) => left.localeCompare(right, "en", { numeric: true }));
  const pairs: PitchAccentMinimalPair[] = [];
  let variantCount = 0;

  for (const fileName of dataFiles) {
    const rawPair = JSON.parse(
      await readFile(path.join(sourceDataDir, fileName), "utf8")
    ) as UpstreamPairFile;
    const options: PitchAccentPairOption[] = [];

    for (const [variantIndex, rawOption] of rawPair.pairs.entries()) {
      const audioBytes = Buffer.from(rawOption.soundData, "base64");
      const codec = sniffAudioCodec(audioBytes);
      const audioRelativePath = path.join(
        "audio",
        fileName,
        `${variantIndex}.${codec.extension}`
      );
      const audioSrc = `/vendor/minimal-pairs/${audioRelativePath.replaceAll(
        path.sep,
        "/"
      )}`;
      const option: PitchAccentPairOption = {
        accentedMora: rawOption.accentedMora,
        audioMime: codec.mime,
        audioSha256: sha256(audioBytes),
        audioSrc,
        byteLength: audioBytes.length,
        id: `${fileName}:${variantIndex}`,
        moraCount: rawOption.moraCount,
        pitchAccent: rawOption.pitchAccent,
        rawPronunciation: rawOption.rawPronunciation,
        silencedMoras: rawOption.silencedMoras
      };

      options.push(option);
      variantCount += 1;
    }

    pairs.push({
      hasDevoiced: options.some((option) => option.silencedMoras.length > 0),
      id: fileName,
      kana: rawPair.kana,
      optionCount: options.length,
      options,
      patternKeys: [
        ...new Set(options.map((option) => getPitchAccentPatternKey(option)))
      ]
    });
  }

  const corpus: PitchAccentMinimalPairsCorpus = {
    pairs,
    source: {
      importedAt,
      license: "GPL-3.0-only",
      repository: input.repositoryUrl,
      revision: input.revision
    },
    version: 1
  };
  const validation = validatePitchAccentMinimalPairsCorpus(corpus);

  if (!validation.ok) {
    throw new Error(
      `Generated minimal-pairs corpus is invalid: ${validation.errors.join(
        "; "
      )}`
    );
  }

  if (!input.dryRun) {
    await assertSafeOutputDir(
      input.outDir,
      input.allowNonVendorOutDir ?? false
    );
    await rm(input.outDir, { recursive: true, force: true });
    await mkdir(path.join(input.outDir, "audio"), { recursive: true });
    await writeFile(
      path.join(input.outDir, GENERATED_MARKER_FILE),
      "Generated by pitch-accent:import-minimal-pairs.\n"
    );

    for (const pair of pairs) {
      for (const option of pair.options) {
        const sourceAudio = Buffer.from(
          await readFile(
            path.join(input.sourceDir, "data", pair.id),
            "utf8"
          ).then((source) => {
            const parsed = JSON.parse(source) as UpstreamPairFile;
            const index = Number(option.id.split(":")[1]);
            return parsed.pairs[index]?.soundData ?? "";
          }),
          "base64"
        );
        const outputPath = path.join(
          input.outDir,
          option.audioSrc.replace("/vendor/minimal-pairs/", "")
        );
        await mkdir(path.dirname(outputPath), { recursive: true });
        await writeFile(outputPath, sourceAudio);
      }
    }

    await writeFile(
      path.join(input.outDir, "manifest.json"),
      `${JSON.stringify(corpus, null, 2)}\n`
    );
    await writeVendorLicense(input.sourceDir, input.outDir);
    await writeFile(
      path.join(input.outDir, "NOTICE.md"),
      buildNotice({
        importedAt,
        repositoryUrl: input.repositoryUrl,
        revision: input.revision
      })
    );
  }

  return {
    audioFileCount: variantCount,
    pairCount: pairs.length,
    variantCount
  };
}

async function assertSafeOutputDir(
  outDir: string,
  allowNonVendorOutDir: boolean
) {
  const resolvedOutDir = path.resolve(outDir);
  const defaultVendorDir = path.resolve(
    process.cwd(),
    "public/vendor/minimal-pairs"
  );

  if (resolvedOutDir === defaultVendorDir) {
    return;
  }

  if (!allowNonVendorOutDir) {
    throw new Error(
      `Refusing to replace non-standard minimal-pairs output directory: ${resolvedOutDir}. ` +
        "Use the default public/vendor/minimal-pairs directory or pass the explicit allowNonVendorOutDir option."
    );
  }

  const cwd = path.resolve(process.cwd());
  const root = path.parse(resolvedOutDir).root;
  const pathFromOutDirToCwd = path.relative(resolvedOutDir, cwd);
  const outDirContainsCwd =
    pathFromOutDirToCwd === "" ||
    (!pathFromOutDirToCwd.startsWith("..") &&
      !path.isAbsolute(pathFromOutDirToCwd));

  if (resolvedOutDir === root || outDirContainsCwd) {
    throw new Error(
      `Refusing to replace dangerous minimal-pairs output directory: ${resolvedOutDir}.`
    );
  }

  const entries: string[] = await readdir(resolvedOutDir).catch(
    (error: unknown) => {
      if (
        error &&
        typeof error === "object" &&
        "code" in error &&
        error.code === "ENOENT"
      ) {
        return [];
      }

      throw error;
    }
  );

  if (entries.length > 0 && !entries.includes(GENERATED_MARKER_FILE)) {
    throw new Error(
      `Refusing to replace non-empty custom minimal-pairs output directory without ${GENERATED_MARKER_FILE}: ${resolvedOutDir}.`
    );
  }
}

type UpstreamPairFile = {
  readonly kana: string;
  readonly pairs: readonly UpstreamPairOption[];
};

type UpstreamPairOption = {
  readonly accentedMora: number;
  readonly moraCount: number;
  readonly pitchAccent: number;
  readonly rawPronunciation: string;
  readonly silencedMoras: readonly number[];
  readonly soundData: string;
};

function sniffAudioCodec(bytes: Buffer) {
  if (bytes.length >= 2 && bytes[0] === 0xff && (bytes[1]! & 0xf0) === 0xf0) {
    return {
      extension: "aac",
      mime: "audio/aac"
    };
  }
  if (bytes.subarray(0, 4).toString("ascii") === "OggS") {
    return {
      extension: "ogg",
      mime: "audio/ogg"
    };
  }
  if (
    bytes.subarray(0, 3).toString("ascii") === "ID3" ||
    (bytes.length >= 2 && bytes[0] === 0xff && (bytes[1]! & 0xe0) === 0xe0)
  ) {
    return {
      extension: "mp3",
      mime: "audio/mpeg"
    };
  }

  throw new Error("Unsupported minimal-pairs audio codec.");
}

function sha256(bytes: Buffer) {
  return createHash("sha256").update(bytes).digest("hex");
}

async function writeVendorLicense(sourceDir: string, outDir: string) {
  const license = await readFile(path.join(sourceDir, "LICENSE"), "utf8");

  if (!license.includes("GNU GENERAL PUBLIC LICENSE")) {
    throw new Error("Upstream GPL license file was not found.");
  }

  await writeFile(path.join(outDir, "LICENSE-GPL-3.0.txt"), license);
}

function buildNotice(input: {
  readonly importedAt: string;
  readonly repositoryUrl: string;
  readonly revision: string;
}) {
  return `# Minimal Pairs Vendor Notice

This directory contains a transformed local copy of the Japanese pitch-accent
minimal-pairs corpus from Kuuuube/minimal-pairs.

- Source: ${input.repositoryUrl}
- Revision: ${input.revision}
- Imported at: ${input.importedAt}
- License: GPL-3.0-only. See LICENSE-GPL-3.0.txt.

The upstream README describes the project as a backup of the original コツ
minimal pairs test, created by k3zi / kotu.io. This app rewrites the runtime UI
and stores only normalized manifest metadata plus decoded static audio files.
`;
}
