import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

export type RepoScopedSkill = {
  name: string;
  description: string;
  path: string;
};

export type TaskClassifier = {
  task: string;
  orientation: string;
  verify: string;
  sourceDocs: string[];
};

export const agentOrientationPath = path.join("docs", "agent-orientation.md");

export const taskClassifiers: TaskClassifier[] = [
  {
    task: "App code or application logic",
    orientation:
      "Stay out of `content/` unless the task explicitly asks for content changes.",
    verify: "`./scripts/with-node.sh pnpm check`",
    sourceDocs: ["AGENTS.md", "README.md", "docs/dev-tooling.md"]
  },
  {
    task: "Routing, DB, importer/sync, auth, cache revalidation, or E2E-covered user flows",
    orientation:
      "Treat this as a wider behavioral change and keep generated DB artifacts generated.",
    verify:
      "`./scripts/with-node.sh pnpm check` and `./scripts/with-node.sh pnpm release:check`",
    sourceDocs: ["AGENTS.md", "docs/local-verification-notes.md"]
  },
  {
    task: "Content-only work through repo-scoped skills",
    orientation:
      "Use the relevant `.agents/skills/*` workflow and edit protected content only through that workflow.",
    verify:
      "Run the skill's `Verification` commands, usually content/import or targeted workflow gates.",
    sourceDocs: [
      "AGENTS.md",
      ".agents/skills/*/SKILL.md",
      "docs/llm-kit/README.md"
    ]
  },
  {
    task: "Pronunciation, Forvo, pitch accent, image, or media asset workflow",
    orientation:
      "Use the canonical content workflow commands and keep sidecar workflow files scoped to the requested media.",
    verify:
      "Run the targeted workflow validation/import command named by the workflow or skill.",
    sourceDocs: [
      "docs/dev-tooling.md",
      "docs/pronunciation-workflow.md",
      "docs/forvo-pronunciation-fetch.md",
      "docs/pitch-accent-workflow.md"
    ]
  },
  {
    task: "Local setup, environment, QA, or agent tooling",
    orientation:
      "Update the related operational docs in the same slice and keep commands behind `./scripts/with-node.sh`.",
    verify:
      "`./scripts/with-node.sh pnpm format:check` plus the smallest targeted tooling test.",
    sourceDocs: ["docs/dev-tooling.md", ".codex/README.md", ".env.example"]
  }
];

const protectedAreas = [
  {
    area: "`content/`",
    rule: "Read-only for app code, bugfixes, and refactors; editable only for explicit editorial/asset/pronunciation tasks or canonical workflows."
  },
  {
    area: "`content/media/**/workflow/**`",
    rule: "Do not edit manually unless the requested task or workflow requires it."
  },
  {
    area: "`drizzle/`",
    rule: "Generated by `./scripts/with-node.sh pnpm db:generate`; do not hand-edit SQL or snapshots."
  },
  {
    area: "Stable IDs",
    rule: "Do not rename `mediaSlug`, `lessonSlug`, `termId`, or equivalent IDs without a DB migration."
  }
];

const keySourceDocs = [
  {
    path: "AGENTS.md",
    purpose:
      "Non-negotiable repo rules, protected areas, verification matrix, product invariants."
  },
  {
    path: "README.md",
    purpose:
      "Product state, route semantics, bootstrap, and high-level architecture."
  },
  {
    path: "docs/dev-tooling.md",
    purpose: "Local runtime, Codex sandbox setup, workflow command notes."
  },
  {
    path: "docs/llm-kit/README.md",
    purpose: "External LLM content kit and content handoff source of truth."
  },
  {
    path: ".codex/README.md",
    purpose: "Codex local action and sandbox configuration."
  },
  {
    path: ".agents/skills/*/SKILL.md",
    purpose:
      "Repo-scoped workflow instructions for protected content/editorial tasks."
  }
];

export async function discoverRepoScopedSkills(
  repositoryRoot: string
): Promise<RepoScopedSkill[]> {
  const skillsRoot = path.join(repositoryRoot, ".agents", "skills");
  let entries: string[];

  try {
    entries = await readdir(skillsRoot);
  } catch {
    return [];
  }

  const skills = await Promise.all(
    entries.map(async (entry) => {
      const skillPath = path.join(skillsRoot, entry, "SKILL.md");

      try {
        const source = await readFile(skillPath, "utf8");
        const frontmatter = parseYamlLikeFrontmatter(source);

        return {
          name: frontmatter.name ?? entry,
          description: frontmatter.description ?? "",
          path: path.posix.join(".agents", "skills", entry, "SKILL.md")
        };
      } catch {
        return null;
      }
    })
  );

  return skills
    .filter((skill): skill is RepoScopedSkill => skill !== null)
    .sort((left, right) => left.name.localeCompare(right.name));
}

export function buildAgentOrientationDocument({
  skills
}: {
  skills: RepoScopedSkill[];
}): string {
  const lines = [
    "# Agent Orientation",
    "",
    "> Generated by `./scripts/with-node.sh pnpm docs:agent-orientation`; do not edit by hand.",
    "",
    "Use this as the first task classifier before changing files. The detailed rules remain in the source docs linked below.",
    "",
    "## Task Classifier",
    "",
    "| Task | Start Here | Verification | Source Docs |",
    "| --- | --- | --- | --- |",
    ...taskClassifiers.map(
      (classifier) =>
        `| ${classifier.task} | ${classifier.orientation} | ${classifier.verify} | ${classifier.sourceDocs.map(formatCode).join(", ")} |`
    ),
    "",
    "## Protected Areas",
    "",
    "| Area | Rule |",
    "| --- | --- |",
    ...protectedAreas.map((item) => `| ${item.area} | ${item.rule} |`),
    "",
    "## Canonical Wrapper",
    "",
    "Run Node and pnpm commands through the repository wrapper:",
    "",
    "```sh",
    "./scripts/with-node.sh pnpm <command>",
    "```",
    "",
    "This keeps local agents on the supported Node 22.x toolchain.",
    "",
    "## Verification Chooser",
    "",
    "- Documentation-only changes: run `./scripts/with-node.sh pnpm format:check` and any targeted doc/tooling check.",
    "- App code or logic: run `./scripts/with-node.sh pnpm check`.",
    "- Routing, DB, importer/sync, auth, cache revalidation, or E2E-covered flows: run `./scripts/with-node.sh pnpm check` and `./scripts/with-node.sh pnpm release:check`.",
    "- Content-only repo-scoped skill work: run the skill's `Verification` section instead of broad app gates.",
    "- If a required gate cannot run, report the exact command and concrete reason.",
    "",
    "## Repo-Scoped Skills",
    "",
    ...formatSkills(skills),
    "",
    "## Key Source Docs",
    "",
    "| Document | Use For |",
    "| --- | --- |",
    ...keySourceDocs.map(
      (doc) => `| ${formatCode(doc.path)} | ${doc.purpose} |`
    ),
    ""
  ];

  return `${lines.join("\n").trimEnd()}\n`;
}

export async function generateAgentOrientation(
  repositoryRoot: string
): Promise<string> {
  const skills = await discoverRepoScopedSkills(repositoryRoot);

  return buildAgentOrientationDocument({ skills });
}

export async function writeAgentOrientation(repositoryRoot: string) {
  const markdown = await generateAgentOrientation(repositoryRoot);
  await writeFile(
    path.join(repositoryRoot, agentOrientationPath),
    markdown,
    "utf8"
  );
}

export async function checkAgentOrientation(repositoryRoot: string) {
  const expected = await generateAgentOrientation(repositoryRoot);
  const targetPath = path.join(repositoryRoot, agentOrientationPath);
  let actual = "";

  try {
    actual = await readFile(targetPath, "utf8");
  } catch {
    return false;
  }

  return actual === expected;
}

function parseYamlLikeFrontmatter(source: string) {
  if (!source.startsWith("---\n")) {
    return {};
  }

  const endIndex = source.indexOf("\n---", 4);

  if (endIndex === -1) {
    return {};
  }

  const frontmatter = source.slice(4, endIndex).split("\n");
  const values: Record<string, string> = {};

  for (const line of frontmatter) {
    const separatorIndex = line.indexOf(":");

    if (separatorIndex === -1) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();

    if (key) {
      values[key] = value.replace(/^["']|["']$/g, "");
    }
  }

  return values;
}

function formatSkills(skills: RepoScopedSkill[]) {
  if (skills.length === 0) {
    return ["No repo-scoped skills found under `.agents/skills/`."];
  }

  return skills.map((skill) => {
    const suffix = skill.description ? `: ${skill.description}` : "";
    return `- ${formatCode(skill.name)} (${formatCode(skill.path)})${suffix}`;
  });
}

function formatCode(value: string) {
  return `\`${value}\``;
}

async function runCli() {
  const repositoryRoot = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    ".."
  );
  const checkOnly = process.argv.includes("--check");

  if (checkOnly) {
    const isCurrent = await checkAgentOrientation(repositoryRoot);

    if (!isCurrent) {
      console.error(
        `${agentOrientationPath} is out of date. Run ./scripts/with-node.sh pnpm docs:agent-orientation.`
      );
      process.exitCode = 1;
      return;
    }

    console.info(`${agentOrientationPath} is up to date.`);
    return;
  }

  await writeAgentOrientation(repositoryRoot);
  console.info(`Wrote ${agentOrientationPath}.`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  try {
    await runCli();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
