import { createHash } from "node:crypto";
import {
  access,
  copyFile,
  mkdir,
  readFile,
  readdir,
  rm,
  stat,
  writeFile
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  isSupportedAudioAssetPath,
  isValidMediaSlugSegment
} from "../src/features/media/server/assets.ts";

export const mediaAudioPublicDirectoryName = "media-audio";
export const mediaAudioGeneratedMarker = ".media-audio-generated";

export type MediaAudioSyncOptions = {
  check?: boolean;
  contentRoot?: string;
  publicRoot?: string;
};

export type MediaAudioManifestEntry = {
  destinationPath: string;
  relativeOutputPath: string;
  sourcePath: string;
};

export type MediaAudioCheckIssue = {
  message: string;
  path: string;
  type: "extra" | "missing" | "stale" | "unsafe";
};

export type MediaAudioSyncResult = {
  files: number;
  outputDirectory: string;
};

export type MediaAudioCheckResult = MediaAudioSyncResult & {
  issues: MediaAudioCheckIssue[];
};

export async function syncMediaAudioAssets(
  options: MediaAudioSyncOptions = {}
): Promise<MediaAudioSyncResult> {
  const paths = resolveMediaAudioPaths(options);
  const manifest = await collectMediaAudioManifest(paths);

  await assertSafeGeneratedOutputDirectory(paths.outputDirectory);
  await rm(paths.outputDirectory, { force: true, recursive: true });
  await mkdir(paths.outputDirectory, { recursive: true });
  await writeFile(
    path.join(paths.outputDirectory, mediaAudioGeneratedMarker),
    "Generated by scripts/sync-media-audio-assets.ts. Do not edit.\n"
  );

  for (const entry of manifest) {
    await mkdir(path.dirname(entry.destinationPath), { recursive: true });
    await copyFile(entry.sourcePath, entry.destinationPath);
  }

  return {
    files: manifest.length,
    outputDirectory: paths.outputDirectory
  };
}

export async function checkMediaAudioAssets(
  options: MediaAudioSyncOptions = {}
): Promise<MediaAudioCheckResult> {
  const paths = resolveMediaAudioPaths(options);
  const manifest = await collectMediaAudioManifest(paths);
  const issues: MediaAudioCheckIssue[] = [];
  const expectedOutputPaths = new Set(
    manifest.map((entry) => entry.relativeOutputPath)
  );

  if (!(await isGeneratedOutputDirectorySafe(paths.outputDirectory))) {
    issues.push({
      message: `Refusing to check ${paths.outputDirectory} because it is not marked as generated.`,
      path: mediaAudioPublicDirectoryName,
      type: "unsafe"
    });
  }

  for (const entry of manifest) {
    if (!(await fileExists(entry.destinationPath))) {
      issues.push({
        message: "Static audio copy is missing.",
        path: entry.relativeOutputPath,
        type: "missing"
      });
      continue;
    }

    if (!(await filesHaveSameHash(entry.sourcePath, entry.destinationPath))) {
      issues.push({
        message: "Static audio copy differs from the content source.",
        path: entry.relativeOutputPath,
        type: "stale"
      });
    }
  }

  for (const outputPath of await listOutputFiles(paths.outputDirectory)) {
    if (outputPath === mediaAudioGeneratedMarker) {
      continue;
    }

    if (!expectedOutputPaths.has(outputPath)) {
      issues.push({
        message: "Static audio copy no longer has a content source.",
        path: outputPath,
        type: "extra"
      });
    }
  }

  return {
    files: manifest.length,
    issues,
    outputDirectory: paths.outputDirectory
  };
}

async function collectMediaAudioManifest(paths: {
  contentRoot: string;
  outputDirectory: string;
}) {
  const mediaRoot = path.join(paths.contentRoot, "media");
  const mediaDirectories = await readDirectoryEntries(mediaRoot);
  const manifest: MediaAudioManifestEntry[] = [];

  for (const mediaDirectory of mediaDirectories) {
    if (!mediaDirectory.isDirectory()) {
      continue;
    }

    const mediaSlug = mediaDirectory.name;

    if (!isValidMediaSlugSegment(mediaSlug)) {
      throw new Error(`Invalid media slug directory: ${mediaSlug}`);
    }

    const audioRoot = path.join(mediaRoot, mediaSlug, "assets", "audio");
    const audioFiles = await listSourceAudioFiles(audioRoot);

    for (const sourcePath of audioFiles) {
      const relativeAudioPath = normalizeRelativePath(
        path.relative(audioRoot, sourcePath)
      );
      const relativeOutputPath = normalizeRelativePath(
        path.join(mediaSlug, "audio", relativeAudioPath)
      );

      manifest.push({
        destinationPath: path.join(paths.outputDirectory, relativeOutputPath),
        relativeOutputPath,
        sourcePath
      });
    }
  }

  return manifest.sort((left, right) =>
    left.relativeOutputPath.localeCompare(right.relativeOutputPath)
  );
}

async function listSourceAudioFiles(directory: string) {
  const entries = await readDirectoryEntries(directory);
  const files: string[] = [];

  for (const entry of entries) {
    const entryPath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await listSourceAudioFiles(entryPath)));
      continue;
    }

    if (entry.isFile() && isSupportedAudioAssetPath(entryPath)) {
      files.push(entryPath);
    }
  }

  return files.sort((left, right) => left.localeCompare(right));
}

async function listOutputFiles(directory: string) {
  const entries = await readDirectoryEntries(directory);
  const files: string[] = [];

  for (const entry of entries) {
    const entryPath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      const nestedFiles = await listOutputFiles(entryPath);
      files.push(
        ...nestedFiles.map((nestedFile) =>
          normalizeRelativePath(path.join(entry.name, nestedFile))
        )
      );
      continue;
    }

    if (entry.isFile()) {
      files.push(entry.name);
    }
  }

  return files.sort((left, right) => left.localeCompare(right));
}

async function assertSafeGeneratedOutputDirectory(outputDirectory: string) {
  if (await isGeneratedOutputDirectorySafe(outputDirectory)) {
    return;
  }

  throw new Error(
    `Refusing to overwrite ${outputDirectory} because it is not empty and does not contain ${mediaAudioGeneratedMarker}.`
  );
}

async function isGeneratedOutputDirectorySafe(outputDirectory: string) {
  const entries = await readDirectoryEntries(outputDirectory);

  if (entries.length === 0) {
    return true;
  }

  return entries.some((entry) => entry.name === mediaAudioGeneratedMarker);
}

async function filesHaveSameHash(leftPath: string, rightPath: string) {
  const [left, right] = await Promise.all([stat(leftPath), stat(rightPath)]);

  if (left.size !== right.size) {
    return false;
  }

  const [leftHash, rightHash] = await Promise.all([
    hashFile(leftPath),
    hashFile(rightPath)
  ]);

  return leftHash === rightHash;
}

async function hashFile(filePath: string) {
  const file = await readFile(filePath);

  return createHash("sha256").update(file).digest("hex");
}

async function fileExists(filePath: string) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readDirectoryEntries(directory: string) {
  try {
    return await readdir(directory, { withFileTypes: true });
  } catch (error) {
    if (isMissingPathError(error)) {
      return [];
    }

    throw error;
  }
}

function resolveMediaAudioPaths(options: MediaAudioSyncOptions) {
  const repositoryRoot = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    ".."
  );
  const contentRoot = options.contentRoot
    ? path.resolve(options.contentRoot)
    : path.resolve(repositoryRoot, "content");
  const publicRoot = options.publicRoot
    ? path.resolve(options.publicRoot)
    : path.resolve(repositoryRoot, "public");

  return {
    contentRoot,
    outputDirectory: path.join(publicRoot, mediaAudioPublicDirectoryName)
  };
}

function normalizeRelativePath(candidate: string) {
  return candidate.replaceAll(path.sep, "/");
}

function isMissingPathError(error: unknown) {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    error.code === "ENOENT"
  );
}

function readCliOptions(argv: string[]): MediaAudioSyncOptions {
  const options: MediaAudioSyncOptions = {};

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];

    if (argument === "--") {
      continue;
    }

    if (argument === "--check") {
      options.check = true;
      continue;
    }

    if (argument === "--content-root") {
      options.contentRoot = path.resolve(readOptionValue(argv, index, argument));
      index += 1;
      continue;
    }

    if (argument === "--public-root") {
      options.publicRoot = path.resolve(readOptionValue(argv, index, argument));
      index += 1;
      continue;
    }

    throw new Error(`Unknown option: ${argument}`);
  }

  return options;
}

function readOptionValue(args: string[], index: number, flag: string) {
  const value = args[index + 1];

  if (!value || value.startsWith("--")) {
    throw new Error(`Missing value for ${flag}.`);
  }

  return value;
}

async function runCli() {
  const options = readCliOptions(process.argv.slice(2));

  if (options.check) {
    const result = await checkMediaAudioAssets(options);

    if (result.issues.length === 0) {
      console.info(
        `media-audio:check passed. ${result.files} audio file(s) current in ${result.outputDirectory}.`
      );
      return;
    }

    console.error(
      `media-audio:check failed. Run pnpm media-audio:sync to update ${result.outputDirectory}.`
    );

    for (const issue of result.issues) {
      console.error(`- [${issue.type}] ${issue.path}: ${issue.message}`);
    }

    process.exitCode = 1;
    return;
  }

  const result = await syncMediaAudioAssets(options);
  console.info(
    `media-audio:sync copied ${result.files} audio file(s) to ${result.outputDirectory}.`
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  try {
    await runCli();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
